#!/bin/bash
# Run coverage & generate html report using Docker & gcovr
echo "running coverage script..."
docker build -t yaksha .
export COV=$(realpath "./bin/coverage")
export FUZZ=$(realpath "./bin/fuzz")
echo "coverage path is $COV"
echo "fuzz path is $FUZZ"
docker run -v "$COV:/coverage" -v "$FUZZ:/fuzz" --rm -it --entrypoint /app/scripts/code-coverage.sh yaksha
