// entry_struct_func_compiler.h
#ifndef ENTRY_STRUCT_COMPILER_H
#define ENTRY_STRUCT_COMPILER_H
#include "datatype_compiler.h"
#include "utilities/ykdt_pool.h"
#include <unordered_map>
namespace yaksha {
  struct entry_data {
    ykdatatype *key_dt_;
    ykdatatype *val_dt_;
    unsigned int incremented_id_;
  };
  struct func_data {
    [[maybe_unused]] ykdatatype *input_type;
    [[maybe_unused]] ykdatatype *output_type;
    [[maybe_unused]] unsigned int increment_id_;
  };
  struct entry_struct_func_compiler {
    explicit entry_struct_func_compiler(ykdt_pool *pool);
    std::string compile(ykdatatype *entry_dt, datatype_compiler *dtc);
    std::string compile_function_dt(ykdatatype *function_dt,
                                    datatype_compiler *dtc);
    void compile_forward_declarations(std::stringstream &target);
    void compile_structures(std::stringstream &target);
    void compile_function_defs(std::stringstream &target);
    bool has_structures();
    bool has_functions();
    ~entry_struct_func_compiler();

private:
    ykdt_pool *pool_;
    // Autogenerated structures
    unsigned int counter_;
    std::vector<entry_data> autogen_structs_list_;
    std::unordered_map<std::string, unsigned int> autogen_structs_;
    std::stringstream code_;
    // Autogenerated function typedefs
    unsigned int counter_functions_;
    std::vector<func_data> autogen_func_typedef_list_;
    std::unordered_map<std::string, unsigned int> autogen_func_typedefs_;
    std::stringstream code_fnc_;
  };
}// namespace yaksha
#endif
