#!/usr/bin/env python
"""
This is going to update token.h
Generate repetitive code in token.h for
    - str_to_token
    - token_to_str
    - keyword_to_token
This also add token and parsing_error structures to the file.
"""
import os.path

REPLACE_TOKENS = "$TOKENS$"
REPLACE_TOKEN_TO_STR = "$TOKEN_TO_STR$"
REPLACE_STR_TO_TOKEN = "$STR_TO_TOKEN$"
REPLACE_STR_TO_KEYWORD = "$STR_TO_KEYWORD$"
REPLACE_SINGLE_TOKEN = "$K$"
REPLACE_UPPER_CASE_SINGLE_TOKEN = "$KU$"
INDENTATION = " " * 4
KEYWORDS = sorted([
    "False", "else", "import", "pass",
    "None", "break", "True", "class", "return",
    "and", "continue", "for", "try", "as",
    "def", "from", "while", "assert", "del", "not",
    "elif", "if", "or", "print"
])
TOKENS = sorted([
    "NAME", "AT", "INTEGER_DECIMAL", "INTEGER_OCT", "INTEGER_HEX", "INTEGER_BIN", "FLOAT_NUMBER", "INDENT",
    "BA_INDENT", "BA_DEDENT", "NEW_LINE", "COLON", "COMMENT", "THREE_QUOTE_STRING", "STRING", "PAREN_OPEN",
    "PAREN_CLOSE", "SQUARE_BRACKET_OPEN", "SQUARE_BRACKET_CLOSE", "CURLY_BRACKET_OPEN", "CURLY_BRACKET_CLOSE", "LESS",
    "EQ", "GREAT", "OR", "PLUS", "SUB", "MUL", "DIV", "AND", "XOR", "MOD", "INT_DIV", "POWER", "LESS_EQ", "EQ_EQ",
    "GREAT_EQ", "OR_EQ", "PLUS_EQ", "SUB_EQ", "MUL_EQ", "DIV_EQ", "AND_EQ", "XOR_EQ", "MOD_EQ", "INT_DIV_EQ",
    "POWER_EQ", "ARROW", "ELLIPSIS", "DOT", "COMMA", "SHL", "SHR", "NOT_EQ", "TILDE", "END_OF_FILE"
]) + ["KEYWORD_" + x.upper() for x in KEYWORDS]
TOKEN_H_TEMPLATE = r"""
// token.h
// generated by update_tokens.py
#ifndef TOKEN_H
#define TOKEN_H
#include <string>
namespace yaksha {
  /**
   * Most simple types of tokens we can match with tokenizing
   */
  enum class token_type {
$TOKENS$
    TK_UNKNOWN_TOKEN_DETECTED
  };
  /**
   * Convert a token to a string
   * @param t token type
   * @return token type as a std::string
   */
  static inline std::string token_to_str(const token_type &t) {
$TOKEN_TO_STR$
    return "TK_UNKNOWN_TOKEN_DETECTED";
  }
  static inline token_type str_to_token(const std::string &t) {
$STR_TO_TOKEN$
    return token_type::TK_UNKNOWN_TOKEN_DETECTED;
  }
  static inline token_type str_to_keyword(const std::string &t) {
$STR_TO_KEYWORD$
    return token_type::TK_UNKNOWN_TOKEN_DETECTED;
  }
  /**
   * Single token
   */
  struct token {
    std::string file_; // filename
    int line_;         // line in file
    int pos_;          // position in line
    std::string token_;// token as a bunch of uint32_t characters
    token_type type_;  // type of the token
  };
  /**
   * Content of an error message
   */
  struct parsing_error {
    std::string message_;// content of the line this error occurred
    token tok_;
    bool token_set_{};
    parsing_error(std::string message, token *at);
    parsing_error(std::string message, std::string file, int line, int pos);
  };
}// namespace yaksha
#endif
""".strip()
STR_TO_TOKEN_TEMPLATE = INDENTATION + r"""if (t == "$K$") { return token_type::$K$; }"""
TOKEN_TO_STR_TEMPLATE = INDENTATION + r"""if (t == token_type::$K$) { return "$K$"; }"""
KEYWORD_TO_TOKEN_TEMPLATE = INDENTATION + r"""if (t == "$K$") { return token_type::KEYWORD_$KU$; }"""


def main():
    token_list = "\n".join([INDENTATION + x + "," for x in TOKENS])
    str_to_token_lines = "\n".join([
        STR_TO_TOKEN_TEMPLATE.replace(REPLACE_SINGLE_TOKEN, x) for x in TOKENS])
    token_to_str_lines = "\n".join([
        TOKEN_TO_STR_TEMPLATE.replace(REPLACE_SINGLE_TOKEN, x) for x in TOKENS])
    str_to_keyword_lines = "\n".join([
        KEYWORD_TO_TOKEN_TEMPLATE.replace(REPLACE_SINGLE_TOKEN, x).replace(
            REPLACE_UPPER_CASE_SINGLE_TOKEN, x.upper())
        for x in KEYWORDS])
    code = TOKEN_H_TEMPLATE.replace(REPLACE_STR_TO_TOKEN, str_to_token_lines) \
        .replace(REPLACE_TOKEN_TO_STR, token_to_str_lines) \
        .replace(REPLACE_STR_TO_KEYWORD, str_to_keyword_lines) \
        .replace(REPLACE_TOKENS, token_list)
    with open(os.path.join(".", "src", "tokenizer", "token.h"), "w+", encoding="utf-8") as h:
        h.write(code)


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.dirname(__file__)))
    main()
