// ast.cpp
// generated by update_ast.py
#include "ast/ast.h"
#include "ast/ast_json_helpers.h"
using namespace yaksha;
// ------- expressions -----
assign_expr::assign_expr(token* name, token* opr, expr* right, bool promoted, yk_datatype* promoted_data_type)
    : name_(name), opr_(opr), right_(right), promoted_(promoted), promoted_data_type_(promoted_data_type) {}
void assign_expr::accept(expr_visitor *v) {
  v->visit_assign_expr(this);
}
ast_type assign_expr::get_type() {
  return ast_type::EXPR_ASSIGN;
}
token* assign_expr::locate() {
  return name_;
}
nlohmann::json assign_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_assign";
  j["name"] = to_json_val(name_);
  j["opr"] = to_json_val(opr_);
  j["right"] = to_json_val(right_);
  j["promoted"] = to_json_val(promoted_);
  j["promoted_data_type"] = to_json_val(promoted_data_type_);
  return j;
}
assign_expr* assign_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<assign_expr*>(pool->c_assign_expr(from_json_val_token(j["name"], pool),
      from_json_val_token(j["opr"], pool),
      from_json_val_expr(j["right"], pool),
      from_json_val_bool(j["promoted"], pool),
      from_json_val_yk_datatype(j["promoted_data_type"], pool)));
}
expr *ast_pool::c_assign_expr(token* name, token* opr, expr* right, bool promoted, yk_datatype* promoted_data_type) {
  auto o = new assign_expr(name, opr, right, promoted, promoted_data_type);
  cleanup_expr_.push_back(o);
  return o;
}
assign_arr_expr::assign_arr_expr(expr* assign_oper, token* opr, expr* right)
    : assign_oper_(assign_oper), opr_(opr), right_(right) {}
void assign_arr_expr::accept(expr_visitor *v) {
  v->visit_assign_arr_expr(this);
}
ast_type assign_arr_expr::get_type() {
  return ast_type::EXPR_ASSIGN_ARR;
}
token* assign_arr_expr::locate() {
  return opr_;
}
nlohmann::json assign_arr_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_assign_arr";
  j["assign_oper"] = to_json_val(assign_oper_);
  j["opr"] = to_json_val(opr_);
  j["right"] = to_json_val(right_);
  return j;
}
assign_arr_expr* assign_arr_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<assign_arr_expr*>(pool->c_assign_arr_expr(from_json_val_expr(j["assign_oper"], pool),
      from_json_val_token(j["opr"], pool),
      from_json_val_expr(j["right"], pool)));
}
expr *ast_pool::c_assign_arr_expr(expr* assign_oper, token* opr, expr* right) {
  auto o = new assign_arr_expr(assign_oper, opr, right);
  cleanup_expr_.push_back(o);
  return o;
}
assign_member_expr::assign_member_expr(expr* set_oper, token* opr, expr* right)
    : set_oper_(set_oper), opr_(opr), right_(right) {}
void assign_member_expr::accept(expr_visitor *v) {
  v->visit_assign_member_expr(this);
}
ast_type assign_member_expr::get_type() {
  return ast_type::EXPR_ASSIGN_MEMBER;
}
token* assign_member_expr::locate() {
  return opr_;
}
nlohmann::json assign_member_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_assign_member";
  j["set_oper"] = to_json_val(set_oper_);
  j["opr"] = to_json_val(opr_);
  j["right"] = to_json_val(right_);
  return j;
}
assign_member_expr* assign_member_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<assign_member_expr*>(pool->c_assign_member_expr(from_json_val_expr(j["set_oper"], pool),
      from_json_val_token(j["opr"], pool),
      from_json_val_expr(j["right"], pool)));
}
expr *ast_pool::c_assign_member_expr(expr* set_oper, token* opr, expr* right) {
  auto o = new assign_member_expr(set_oper, opr, right);
  cleanup_expr_.push_back(o);
  return o;
}
binary_expr::binary_expr(expr* left, token* opr, expr* right)
    : left_(left), opr_(opr), right_(right) {}
void binary_expr::accept(expr_visitor *v) {
  v->visit_binary_expr(this);
}
ast_type binary_expr::get_type() {
  return ast_type::EXPR_BINARY;
}
token* binary_expr::locate() {
  return opr_;
}
nlohmann::json binary_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_binary";
  j["left"] = to_json_val(left_);
  j["opr"] = to_json_val(opr_);
  j["right"] = to_json_val(right_);
  return j;
}
binary_expr* binary_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<binary_expr*>(pool->c_binary_expr(from_json_val_expr(j["left"], pool),
      from_json_val_token(j["opr"], pool),
      from_json_val_expr(j["right"], pool)));
}
expr *ast_pool::c_binary_expr(expr* left, token* opr, expr* right) {
  auto o = new binary_expr(left, opr, right);
  cleanup_expr_.push_back(o);
  return o;
}
curly_call_expr::curly_call_expr(expr* dt_expr, token* curly_open, std::vector<name_val> values, token* curly_close)
    : dt_expr_(dt_expr), curly_open_(curly_open), values_(std::move(values)), curly_close_(curly_close) {}
void curly_call_expr::accept(expr_visitor *v) {
  v->visit_curly_call_expr(this);
}
ast_type curly_call_expr::get_type() {
  return ast_type::EXPR_CURLY_CALL;
}
token* curly_call_expr::locate() {
  return curly_open_;
}
nlohmann::json curly_call_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_curly_call";
  j["dt_expr"] = to_json_val(dt_expr_);
  j["curly_open"] = to_json_val(curly_open_);
  j["values"] = to_json_val(values_);
  j["curly_close"] = to_json_val(curly_close_);
  return j;
}
curly_call_expr* curly_call_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<curly_call_expr*>(pool->c_curly_call_expr(from_json_val_expr(j["dt_expr"], pool),
      from_json_val_token(j["curly_open"], pool),
      from_json_val_vector_helper(j["values"], [&](const nlohmann::json& item) { return from_json_val_name_val(item, pool); }),
      from_json_val_token(j["curly_close"], pool)));
}
expr *ast_pool::c_curly_call_expr(expr* dt_expr, token* curly_open, std::vector<name_val> values, token* curly_close) {
  auto o = new curly_call_expr(dt_expr, curly_open, std::move(values), curly_close);
  cleanup_expr_.push_back(o);
  return o;
}
fncall_expr::fncall_expr(expr* name, token* paren_token, std::vector<expr*> args)
    : name_(name), paren_token_(paren_token), args_(std::move(args)) {}
void fncall_expr::accept(expr_visitor *v) {
  v->visit_fncall_expr(this);
}
ast_type fncall_expr::get_type() {
  return ast_type::EXPR_FNCALL;
}
token* fncall_expr::locate() {
  return name_->locate();
}
nlohmann::json fncall_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_fncall";
  j["name"] = to_json_val(name_);
  j["paren_token"] = to_json_val(paren_token_);
  j["args"] = to_json_val(args_);
  return j;
}
fncall_expr* fncall_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<fncall_expr*>(pool->c_fncall_expr(from_json_val_expr(j["name"], pool),
      from_json_val_token(j["paren_token"], pool),
      from_json_val_vector_helper(j["args"], [&](const nlohmann::json& item) { return from_json_val_expr(item, pool); })));
}
expr *ast_pool::c_fncall_expr(expr* name, token* paren_token, std::vector<expr*> args) {
  auto o = new fncall_expr(name, paren_token, std::move(args));
  cleanup_expr_.push_back(o);
  return o;
}
get_expr::get_expr(expr* lhs, token* dot, token* item)
    : lhs_(lhs), dot_(dot), item_(item) {}
void get_expr::accept(expr_visitor *v) {
  v->visit_get_expr(this);
}
ast_type get_expr::get_type() {
  return ast_type::EXPR_GET;
}
token* get_expr::locate() {
  return dot_;
}
nlohmann::json get_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_get";
  j["lhs"] = to_json_val(lhs_);
  j["dot"] = to_json_val(dot_);
  j["item"] = to_json_val(item_);
  return j;
}
get_expr* get_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<get_expr*>(pool->c_get_expr(from_json_val_expr(j["lhs"], pool),
      from_json_val_token(j["dot"], pool),
      from_json_val_token(j["item"], pool)));
}
expr *ast_pool::c_get_expr(expr* lhs, token* dot, token* item) {
  auto o = new get_expr(lhs, dot, item);
  cleanup_expr_.push_back(o);
  return o;
}
grouping_expr::grouping_expr(expr* expression)
    : expression_(expression) {}
void grouping_expr::accept(expr_visitor *v) {
  v->visit_grouping_expr(this);
}
ast_type grouping_expr::get_type() {
  return ast_type::EXPR_GROUPING;
}
token* grouping_expr::locate() {
  return expression_->locate();
}
nlohmann::json grouping_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_grouping";
  j["expression"] = to_json_val(expression_);
  return j;
}
grouping_expr* grouping_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<grouping_expr*>(pool->c_grouping_expr(from_json_val_expr(j["expression"], pool)));
}
expr *ast_pool::c_grouping_expr(expr* expression) {
  auto o = new grouping_expr(expression);
  cleanup_expr_.push_back(o);
  return o;
}
literal_expr::literal_expr(token* literal_token)
    : literal_token_(literal_token) {}
void literal_expr::accept(expr_visitor *v) {
  v->visit_literal_expr(this);
}
ast_type literal_expr::get_type() {
  return ast_type::EXPR_LITERAL;
}
token* literal_expr::locate() {
  return literal_token_;
}
nlohmann::json literal_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_literal";
  j["literal_token"] = to_json_val(literal_token_);
  return j;
}
literal_expr* literal_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<literal_expr*>(pool->c_literal_expr(from_json_val_token(j["literal_token"], pool)));
}
expr *ast_pool::c_literal_expr(token* literal_token) {
  auto o = new literal_expr(literal_token);
  cleanup_expr_.push_back(o);
  return o;
}
logical_expr::logical_expr(expr* left, token* opr, expr* right)
    : left_(left), opr_(opr), right_(right) {}
void logical_expr::accept(expr_visitor *v) {
  v->visit_logical_expr(this);
}
ast_type logical_expr::get_type() {
  return ast_type::EXPR_LOGICAL;
}
token* logical_expr::locate() {
  return opr_;
}
nlohmann::json logical_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_logical";
  j["left"] = to_json_val(left_);
  j["opr"] = to_json_val(opr_);
  j["right"] = to_json_val(right_);
  return j;
}
logical_expr* logical_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<logical_expr*>(pool->c_logical_expr(from_json_val_expr(j["left"], pool),
      from_json_val_token(j["opr"], pool),
      from_json_val_expr(j["right"], pool)));
}
expr *ast_pool::c_logical_expr(expr* left, token* opr, expr* right) {
  auto o = new logical_expr(left, opr, right);
  cleanup_expr_.push_back(o);
  return o;
}
macro_call_expr::macro_call_expr(token* path, token* name, token* not_symbol_tok, token* paren_token, std::vector<expr*> args, token* close_paren_token)
    : path_(path), name_(name), not_symbol_tok_(not_symbol_tok), paren_token_(paren_token), args_(std::move(args)), close_paren_token_(close_paren_token) {}
void macro_call_expr::accept(expr_visitor *v) {
  v->visit_macro_call_expr(this);
}
ast_type macro_call_expr::get_type() {
  return ast_type::EXPR_MACRO_CALL;
}
token* macro_call_expr::locate() {
  return name_;
}
nlohmann::json macro_call_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_macro_call";
  j["path"] = to_json_val(path_);
  j["name"] = to_json_val(name_);
  j["not_symbol_tok"] = to_json_val(not_symbol_tok_);
  j["paren_token"] = to_json_val(paren_token_);
  j["args"] = to_json_val(args_);
  j["close_paren_token"] = to_json_val(close_paren_token_);
  return j;
}
macro_call_expr* macro_call_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<macro_call_expr*>(pool->c_macro_call_expr(from_json_val_token(j["path"], pool),
      from_json_val_token(j["name"], pool),
      from_json_val_token(j["not_symbol_tok"], pool),
      from_json_val_token(j["paren_token"], pool),
      from_json_val_vector_helper(j["args"], [&](const nlohmann::json& item) { return from_json_val_expr(item, pool); }),
      from_json_val_token(j["close_paren_token"], pool)));
}
expr *ast_pool::c_macro_call_expr(token* path, token* name, token* not_symbol_tok, token* paren_token, std::vector<expr*> args, token* close_paren_token) {
  auto o = new macro_call_expr(path, name, not_symbol_tok, paren_token, std::move(args), close_paren_token);
  cleanup_expr_.push_back(o);
  return o;
}
set_expr::set_expr(expr* lhs, token* dot, token* item)
    : lhs_(lhs), dot_(dot), item_(item) {}
void set_expr::accept(expr_visitor *v) {
  v->visit_set_expr(this);
}
ast_type set_expr::get_type() {
  return ast_type::EXPR_SET;
}
token* set_expr::locate() {
  return dot_;
}
nlohmann::json set_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_set";
  j["lhs"] = to_json_val(lhs_);
  j["dot"] = to_json_val(dot_);
  j["item"] = to_json_val(item_);
  return j;
}
set_expr* set_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<set_expr*>(pool->c_set_expr(from_json_val_expr(j["lhs"], pool),
      from_json_val_token(j["dot"], pool),
      from_json_val_token(j["item"], pool)));
}
expr *ast_pool::c_set_expr(expr* lhs, token* dot, token* item) {
  auto o = new set_expr(lhs, dot, item);
  cleanup_expr_.push_back(o);
  return o;
}
square_bracket_access_expr::square_bracket_access_expr(expr* name, token* sqb_token, expr* index_expr)
    : name_(name), sqb_token_(sqb_token), index_expr_(index_expr) {}
void square_bracket_access_expr::accept(expr_visitor *v) {
  v->visit_square_bracket_access_expr(this);
}
ast_type square_bracket_access_expr::get_type() {
  return ast_type::EXPR_SQUARE_BRACKET_ACCESS;
}
token* square_bracket_access_expr::locate() {
  return sqb_token_;
}
nlohmann::json square_bracket_access_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_square_bracket_access";
  j["name"] = to_json_val(name_);
  j["sqb_token"] = to_json_val(sqb_token_);
  j["index_expr"] = to_json_val(index_expr_);
  return j;
}
square_bracket_access_expr* square_bracket_access_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<square_bracket_access_expr*>(pool->c_square_bracket_access_expr(from_json_val_expr(j["name"], pool),
      from_json_val_token(j["sqb_token"], pool),
      from_json_val_expr(j["index_expr"], pool)));
}
expr *ast_pool::c_square_bracket_access_expr(expr* name, token* sqb_token, expr* index_expr) {
  auto o = new square_bracket_access_expr(name, sqb_token, index_expr);
  cleanup_expr_.push_back(o);
  return o;
}
square_bracket_set_expr::square_bracket_set_expr(expr* name, token* sqb_token, expr* index_expr)
    : name_(name), sqb_token_(sqb_token), index_expr_(index_expr) {}
void square_bracket_set_expr::accept(expr_visitor *v) {
  v->visit_square_bracket_set_expr(this);
}
ast_type square_bracket_set_expr::get_type() {
  return ast_type::EXPR_SQUARE_BRACKET_SET;
}
token* square_bracket_set_expr::locate() {
  return sqb_token_;
}
nlohmann::json square_bracket_set_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_square_bracket_set";
  j["name"] = to_json_val(name_);
  j["sqb_token"] = to_json_val(sqb_token_);
  j["index_expr"] = to_json_val(index_expr_);
  return j;
}
square_bracket_set_expr* square_bracket_set_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<square_bracket_set_expr*>(pool->c_square_bracket_set_expr(from_json_val_expr(j["name"], pool),
      from_json_val_token(j["sqb_token"], pool),
      from_json_val_expr(j["index_expr"], pool)));
}
expr *ast_pool::c_square_bracket_set_expr(expr* name, token* sqb_token, expr* index_expr) {
  auto o = new square_bracket_set_expr(name, sqb_token, index_expr);
  cleanup_expr_.push_back(o);
  return o;
}
unary_expr::unary_expr(token* opr, expr* right)
    : opr_(opr), right_(right) {}
void unary_expr::accept(expr_visitor *v) {
  v->visit_unary_expr(this);
}
ast_type unary_expr::get_type() {
  return ast_type::EXPR_UNARY;
}
token* unary_expr::locate() {
  return opr_;
}
nlohmann::json unary_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_unary";
  j["opr"] = to_json_val(opr_);
  j["right"] = to_json_val(right_);
  return j;
}
unary_expr* unary_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<unary_expr*>(pool->c_unary_expr(from_json_val_token(j["opr"], pool),
      from_json_val_expr(j["right"], pool)));
}
expr *ast_pool::c_unary_expr(token* opr, expr* right) {
  auto o = new unary_expr(opr, right);
  cleanup_expr_.push_back(o);
  return o;
}
variable_expr::variable_expr(token* name)
    : name_(name) {}
void variable_expr::accept(expr_visitor *v) {
  v->visit_variable_expr(this);
}
ast_type variable_expr::get_type() {
  return ast_type::EXPR_VARIABLE;
}
token* variable_expr::locate() {
  return name_;
}
nlohmann::json variable_expr::to_json() {
  nlohmann::json j;
  j["ast_type"] = "expr_variable";
  j["name"] = to_json_val(name_);
  return j;
}
variable_expr* variable_expr::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<variable_expr*>(pool->c_variable_expr(from_json_val_token(j["name"], pool)));
}
expr *ast_pool::c_variable_expr(token* name) {
  auto o = new variable_expr(name);
  cleanup_expr_.push_back(o);
  return o;
}
// ------- statements -----
block_stmt::block_stmt(std::vector<stmt*> statements)
    : statements_(std::move(statements)) {}
void block_stmt::accept(stmt_visitor *v) {
  v->visit_block_stmt(this);
}
ast_type block_stmt::get_type() {
  return ast_type::STMT_BLOCK;
}
token* block_stmt::locate() {
  return statements_[0]->locate();
}
nlohmann::json block_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_block";
  j["statements"] = to_json_val(statements_);
  return j;
}
block_stmt* block_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<block_stmt*>(pool->c_block_stmt(from_json_val_vector_helper(j["statements"], [&](const nlohmann::json& item) { return from_json_val_stmt(item, pool); })));
}
stmt *ast_pool::c_block_stmt(std::vector<stmt*> statements) {
  auto o = new block_stmt(std::move(statements));
  cleanup_stmt_.push_back(o);
  return o;
}
break_stmt::break_stmt(token* break_token)
    : break_token_(break_token) {}
void break_stmt::accept(stmt_visitor *v) {
  v->visit_break_stmt(this);
}
ast_type break_stmt::get_type() {
  return ast_type::STMT_BREAK;
}
token* break_stmt::locate() {
  return break_token_;
}
nlohmann::json break_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_break";
  j["break_token"] = to_json_val(break_token_);
  return j;
}
break_stmt* break_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<break_stmt*>(pool->c_break_stmt(from_json_val_token(j["break_token"], pool)));
}
stmt *ast_pool::c_break_stmt(token* break_token) {
  auto o = new break_stmt(break_token);
  cleanup_stmt_.push_back(o);
  return o;
}
ccode_stmt::ccode_stmt(token* ccode_keyword, token* code_str)
    : ccode_keyword_(ccode_keyword), code_str_(code_str) {}
void ccode_stmt::accept(stmt_visitor *v) {
  v->visit_ccode_stmt(this);
}
ast_type ccode_stmt::get_type() {
  return ast_type::STMT_CCODE;
}
token* ccode_stmt::locate() {
  return ccode_keyword_;
}
nlohmann::json ccode_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_ccode";
  j["ccode_keyword"] = to_json_val(ccode_keyword_);
  j["code_str"] = to_json_val(code_str_);
  return j;
}
ccode_stmt* ccode_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<ccode_stmt*>(pool->c_ccode_stmt(from_json_val_token(j["ccode_keyword"], pool),
      from_json_val_token(j["code_str"], pool)));
}
stmt *ast_pool::c_ccode_stmt(token* ccode_keyword, token* code_str) {
  auto o = new ccode_stmt(ccode_keyword, code_str);
  cleanup_stmt_.push_back(o);
  return o;
}
cfor_stmt::cfor_stmt(token* for_keyword, token* open_paren, expr* init_expr, token* semi1, expr* comparison, token* semi2, expr* operation, token* close_paren, stmt* for_body)
    : for_keyword_(for_keyword), open_paren_(open_paren), init_expr_(init_expr), semi1_(semi1), comparison_(comparison), semi2_(semi2), operation_(operation), close_paren_(close_paren), for_body_(for_body) {}
void cfor_stmt::accept(stmt_visitor *v) {
  v->visit_cfor_stmt(this);
}
ast_type cfor_stmt::get_type() {
  return ast_type::STMT_CFOR;
}
token* cfor_stmt::locate() {
  return for_keyword_;
}
nlohmann::json cfor_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_cfor";
  j["for_keyword"] = to_json_val(for_keyword_);
  j["open_paren"] = to_json_val(open_paren_);
  j["init_expr"] = to_json_val(init_expr_);
  j["semi1"] = to_json_val(semi1_);
  j["comparison"] = to_json_val(comparison_);
  j["semi2"] = to_json_val(semi2_);
  j["operation"] = to_json_val(operation_);
  j["close_paren"] = to_json_val(close_paren_);
  j["for_body"] = to_json_val(for_body_);
  return j;
}
cfor_stmt* cfor_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<cfor_stmt*>(pool->c_cfor_stmt(from_json_val_token(j["for_keyword"], pool),
      from_json_val_token(j["open_paren"], pool),
      from_json_val_expr(j["init_expr"], pool),
      from_json_val_token(j["semi1"], pool),
      from_json_val_expr(j["comparison"], pool),
      from_json_val_token(j["semi2"], pool),
      from_json_val_expr(j["operation"], pool),
      from_json_val_token(j["close_paren"], pool),
      from_json_val_stmt(j["for_body"], pool)));
}
stmt *ast_pool::c_cfor_stmt(token* for_keyword, token* open_paren, expr* init_expr, token* semi1, expr* comparison, token* semi2, expr* operation, token* close_paren, stmt* for_body) {
  auto o = new cfor_stmt(for_keyword, open_paren, init_expr, semi1, comparison, semi2, operation, close_paren, for_body);
  cleanup_stmt_.push_back(o);
  return o;
}
class_stmt::class_stmt(token* name, std::vector<parameter> members, annotations annotations)
    : name_(name), members_(std::move(members)), annotations_(annotations) {}
void class_stmt::accept(stmt_visitor *v) {
  v->visit_class_stmt(this);
}
ast_type class_stmt::get_type() {
  return ast_type::STMT_CLASS;
}
token* class_stmt::locate() {
  return name_;
}
nlohmann::json class_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_class";
  j["name"] = to_json_val(name_);
  j["members"] = to_json_val(members_);
  j["annotations"] = to_json_val(annotations_);
  return j;
}
class_stmt* class_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<class_stmt*>(pool->c_class_stmt(from_json_val_token(j["name"], pool),
      from_json_val_vector_helper(j["members"], [&](const nlohmann::json& item) { return from_json_val_parameter(item, pool); }),
      from_json_val_annotations(j["annotations"], pool)));
}
stmt *ast_pool::c_class_stmt(token* name, std::vector<parameter> members, annotations annotations) {
  auto o = new class_stmt(name, std::move(members), annotations);
  cleanup_stmt_.push_back(o);
  return o;
}
compins_stmt::compins_stmt(token* name, yk_datatype* data_type, token* meta1, yk_datatype* meta2, void* meta3)
    : name_(name), data_type_(data_type), meta1_(meta1), meta2_(meta2), meta3_(meta3) {}
void compins_stmt::accept(stmt_visitor *v) {
  v->visit_compins_stmt(this);
}
ast_type compins_stmt::get_type() {
  return ast_type::STMT_COMPINS;
}
token* compins_stmt::locate() {
  return name_;
}
nlohmann::json compins_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_compins";
  j["name"] = to_json_val(name_);
  j["data_type"] = to_json_val(data_type_);
  j["meta1"] = to_json_val(meta1_);
  j["meta2"] = to_json_val(meta2_);
  j["meta3"] = to_json_val(meta3_);
  return j;
}
compins_stmt* compins_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<compins_stmt*>(pool->c_compins_stmt(from_json_val_token(j["name"], pool),
      from_json_val_yk_datatype(j["data_type"], pool),
      from_json_val_token(j["meta1"], pool),
      from_json_val_yk_datatype(j["meta2"], pool),
      from_json_val_void_ptr(j["meta3"], pool)));
}
stmt *ast_pool::c_compins_stmt(token* name, yk_datatype* data_type, token* meta1, yk_datatype* meta2, void* meta3) {
  auto o = new compins_stmt(name, data_type, meta1, meta2, meta3);
  cleanup_stmt_.push_back(o);
  return o;
}
const_stmt::const_stmt(token* name, yk_datatype* data_type, expr* expression, bool is_global)
    : name_(name), data_type_(data_type), expression_(expression), is_global_(is_global) {}
void const_stmt::accept(stmt_visitor *v) {
  v->visit_const_stmt(this);
}
ast_type const_stmt::get_type() {
  return ast_type::STMT_CONST;
}
token* const_stmt::locate() {
  return name_;
}
nlohmann::json const_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_const";
  j["name"] = to_json_val(name_);
  j["data_type"] = to_json_val(data_type_);
  j["expression"] = to_json_val(expression_);
  j["is_global"] = to_json_val(is_global_);
  return j;
}
const_stmt* const_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<const_stmt*>(pool->c_const_stmt(from_json_val_token(j["name"], pool),
      from_json_val_yk_datatype(j["data_type"], pool),
      from_json_val_expr(j["expression"], pool),
      from_json_val_bool(j["is_global"], pool)));
}
stmt *ast_pool::c_const_stmt(token* name, yk_datatype* data_type, expr* expression, bool is_global) {
  auto o = new const_stmt(name, data_type, expression, is_global);
  cleanup_stmt_.push_back(o);
  return o;
}
continue_stmt::continue_stmt(token* continue_token)
    : continue_token_(continue_token) {}
void continue_stmt::accept(stmt_visitor *v) {
  v->visit_continue_stmt(this);
}
ast_type continue_stmt::get_type() {
  return ast_type::STMT_CONTINUE;
}
token* continue_stmt::locate() {
  return continue_token_;
}
nlohmann::json continue_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_continue";
  j["continue_token"] = to_json_val(continue_token_);
  return j;
}
continue_stmt* continue_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<continue_stmt*>(pool->c_continue_stmt(from_json_val_token(j["continue_token"], pool)));
}
stmt *ast_pool::c_continue_stmt(token* continue_token) {
  auto o = new continue_stmt(continue_token);
  cleanup_stmt_.push_back(o);
  return o;
}
def_stmt::def_stmt(token* name, std::vector<parameter> params, stmt* function_body, yk_datatype* return_type, annotations annotations)
    : name_(name), params_(std::move(params)), function_body_(function_body), return_type_(return_type), annotations_(annotations) {}
void def_stmt::accept(stmt_visitor *v) {
  v->visit_def_stmt(this);
}
ast_type def_stmt::get_type() {
  return ast_type::STMT_DEF;
}
token* def_stmt::locate() {
  return name_;
}
nlohmann::json def_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_def";
  j["name"] = to_json_val(name_);
  j["params"] = to_json_val(params_);
  j["function_body"] = to_json_val(function_body_);
  j["return_type"] = to_json_val(return_type_);
  j["annotations"] = to_json_val(annotations_);
  return j;
}
def_stmt* def_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<def_stmt*>(pool->c_def_stmt(from_json_val_token(j["name"], pool),
      from_json_val_vector_helper(j["params"], [&](const nlohmann::json& item) { return from_json_val_parameter(item, pool); }),
      from_json_val_stmt(j["function_body"], pool),
      from_json_val_yk_datatype(j["return_type"], pool),
      from_json_val_annotations(j["annotations"], pool)));
}
stmt *ast_pool::c_def_stmt(token* name, std::vector<parameter> params, stmt* function_body, yk_datatype* return_type, annotations annotations) {
  auto o = new def_stmt(name, std::move(params), function_body, return_type, annotations);
  cleanup_stmt_.push_back(o);
  return o;
}
defer_stmt::defer_stmt(token* defer_keyword, expr* expression, stmt* del_statement)
    : defer_keyword_(defer_keyword), expression_(expression), del_statement_(del_statement) {}
void defer_stmt::accept(stmt_visitor *v) {
  v->visit_defer_stmt(this);
}
ast_type defer_stmt::get_type() {
  return ast_type::STMT_DEFER;
}
token* defer_stmt::locate() {
  return defer_keyword_;
}
nlohmann::json defer_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_defer";
  j["defer_keyword"] = to_json_val(defer_keyword_);
  j["expression"] = to_json_val(expression_);
  j["del_statement"] = to_json_val(del_statement_);
  return j;
}
defer_stmt* defer_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<defer_stmt*>(pool->c_defer_stmt(from_json_val_token(j["defer_keyword"], pool),
      from_json_val_expr(j["expression"], pool),
      from_json_val_stmt(j["del_statement"], pool)));
}
stmt *ast_pool::c_defer_stmt(token* defer_keyword, expr* expression, stmt* del_statement) {
  auto o = new defer_stmt(defer_keyword, expression, del_statement);
  cleanup_stmt_.push_back(o);
  return o;
}
del_stmt::del_stmt(token* del_keyword, expr* expression)
    : del_keyword_(del_keyword), expression_(expression) {}
void del_stmt::accept(stmt_visitor *v) {
  v->visit_del_stmt(this);
}
ast_type del_stmt::get_type() {
  return ast_type::STMT_DEL;
}
token* del_stmt::locate() {
  return del_keyword_;
}
nlohmann::json del_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_del";
  j["del_keyword"] = to_json_val(del_keyword_);
  j["expression"] = to_json_val(expression_);
  return j;
}
del_stmt* del_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<del_stmt*>(pool->c_del_stmt(from_json_val_token(j["del_keyword"], pool),
      from_json_val_expr(j["expression"], pool)));
}
stmt *ast_pool::c_del_stmt(token* del_keyword, expr* expression) {
  auto o = new del_stmt(del_keyword, expression);
  cleanup_stmt_.push_back(o);
  return o;
}
directive_stmt::directive_stmt(token* directive_token, std::vector<parameter> values, token* directive_type, token* directive_val)
    : directive_token_(directive_token), values_(std::move(values)), directive_type_(directive_type), directive_val_(directive_val) {}
void directive_stmt::accept(stmt_visitor *v) {
  v->visit_directive_stmt(this);
}
ast_type directive_stmt::get_type() {
  return ast_type::STMT_DIRECTIVE;
}
token* directive_stmt::locate() {
  return directive_token_;
}
nlohmann::json directive_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_directive";
  j["directive_token"] = to_json_val(directive_token_);
  j["values"] = to_json_val(values_);
  j["directive_type"] = to_json_val(directive_type_);
  j["directive_val"] = to_json_val(directive_val_);
  return j;
}
directive_stmt* directive_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<directive_stmt*>(pool->c_directive_stmt(from_json_val_token(j["directive_token"], pool),
      from_json_val_vector_helper(j["values"], [&](const nlohmann::json& item) { return from_json_val_parameter(item, pool); }),
      from_json_val_token(j["directive_type"], pool),
      from_json_val_token(j["directive_val"], pool)));
}
stmt *ast_pool::c_directive_stmt(token* directive_token, std::vector<parameter> values, token* directive_type, token* directive_val) {
  auto o = new directive_stmt(directive_token, std::move(values), directive_type, directive_val);
  cleanup_stmt_.push_back(o);
  return o;
}
enum_stmt::enum_stmt(token* name, std::vector<parameter> members, annotations annotations)
    : name_(name), members_(std::move(members)), annotations_(annotations) {}
void enum_stmt::accept(stmt_visitor *v) {
  v->visit_enum_stmt(this);
}
ast_type enum_stmt::get_type() {
  return ast_type::STMT_ENUM;
}
token* enum_stmt::locate() {
  return name_;
}
nlohmann::json enum_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_enum";
  j["name"] = to_json_val(name_);
  j["members"] = to_json_val(members_);
  j["annotations"] = to_json_val(annotations_);
  return j;
}
enum_stmt* enum_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<enum_stmt*>(pool->c_enum_stmt(from_json_val_token(j["name"], pool),
      from_json_val_vector_helper(j["members"], [&](const nlohmann::json& item) { return from_json_val_parameter(item, pool); }),
      from_json_val_annotations(j["annotations"], pool)));
}
stmt *ast_pool::c_enum_stmt(token* name, std::vector<parameter> members, annotations annotations) {
  auto o = new enum_stmt(name, std::move(members), annotations);
  cleanup_stmt_.push_back(o);
  return o;
}
expression_stmt::expression_stmt(expr* expression)
    : expression_(expression) {}
void expression_stmt::accept(stmt_visitor *v) {
  v->visit_expression_stmt(this);
}
ast_type expression_stmt::get_type() {
  return ast_type::STMT_EXPRESSION;
}
token* expression_stmt::locate() {
  return expression_->locate();
}
nlohmann::json expression_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_expression";
  j["expression"] = to_json_val(expression_);
  return j;
}
expression_stmt* expression_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<expression_stmt*>(pool->c_expression_stmt(from_json_val_expr(j["expression"], pool)));
}
stmt *ast_pool::c_expression_stmt(expr* expression) {
  auto o = new expression_stmt(expression);
  cleanup_stmt_.push_back(o);
  return o;
}
foreach_stmt::foreach_stmt(token* for_keyword, token* name, yk_datatype* data_type, token* in_keyword, expr* expression, stmt* for_body, yk_datatype* expr_datatype)
    : for_keyword_(for_keyword), name_(name), data_type_(data_type), in_keyword_(in_keyword), expression_(expression), for_body_(for_body), expr_datatype_(expr_datatype) {}
void foreach_stmt::accept(stmt_visitor *v) {
  v->visit_foreach_stmt(this);
}
ast_type foreach_stmt::get_type() {
  return ast_type::STMT_FOREACH;
}
token* foreach_stmt::locate() {
  return for_keyword_;
}
nlohmann::json foreach_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_foreach";
  j["for_keyword"] = to_json_val(for_keyword_);
  j["name"] = to_json_val(name_);
  j["data_type"] = to_json_val(data_type_);
  j["in_keyword"] = to_json_val(in_keyword_);
  j["expression"] = to_json_val(expression_);
  j["for_body"] = to_json_val(for_body_);
  j["expr_datatype"] = to_json_val(expr_datatype_);
  return j;
}
foreach_stmt* foreach_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<foreach_stmt*>(pool->c_foreach_stmt(from_json_val_token(j["for_keyword"], pool),
      from_json_val_token(j["name"], pool),
      from_json_val_yk_datatype(j["data_type"], pool),
      from_json_val_token(j["in_keyword"], pool),
      from_json_val_expr(j["expression"], pool),
      from_json_val_stmt(j["for_body"], pool),
      from_json_val_yk_datatype(j["expr_datatype"], pool)));
}
stmt *ast_pool::c_foreach_stmt(token* for_keyword, token* name, yk_datatype* data_type, token* in_keyword, expr* expression, stmt* for_body, yk_datatype* expr_datatype) {
  auto o = new foreach_stmt(for_keyword, name, data_type, in_keyword, expression, for_body, expr_datatype);
  cleanup_stmt_.push_back(o);
  return o;
}
forendless_stmt::forendless_stmt(token* for_keyword, stmt* for_body)
    : for_keyword_(for_keyword), for_body_(for_body) {}
void forendless_stmt::accept(stmt_visitor *v) {
  v->visit_forendless_stmt(this);
}
ast_type forendless_stmt::get_type() {
  return ast_type::STMT_FORENDLESS;
}
token* forendless_stmt::locate() {
  return for_keyword_;
}
nlohmann::json forendless_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_forendless";
  j["for_keyword"] = to_json_val(for_keyword_);
  j["for_body"] = to_json_val(for_body_);
  return j;
}
forendless_stmt* forendless_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<forendless_stmt*>(pool->c_forendless_stmt(from_json_val_token(j["for_keyword"], pool),
      from_json_val_stmt(j["for_body"], pool)));
}
stmt *ast_pool::c_forendless_stmt(token* for_keyword, stmt* for_body) {
  auto o = new forendless_stmt(for_keyword, for_body);
  cleanup_stmt_.push_back(o);
  return o;
}
if_stmt::if_stmt(token* if_keyword, expr* expression, stmt* if_branch, token* else_keyword, stmt* else_branch)
    : if_keyword_(if_keyword), expression_(expression), if_branch_(if_branch), else_keyword_(else_keyword), else_branch_(else_branch) {}
void if_stmt::accept(stmt_visitor *v) {
  v->visit_if_stmt(this);
}
ast_type if_stmt::get_type() {
  return ast_type::STMT_IF;
}
token* if_stmt::locate() {
  return if_keyword_;
}
nlohmann::json if_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_if";
  j["if_keyword"] = to_json_val(if_keyword_);
  j["expression"] = to_json_val(expression_);
  j["if_branch"] = to_json_val(if_branch_);
  j["else_keyword"] = to_json_val(else_keyword_);
  j["else_branch"] = to_json_val(else_branch_);
  return j;
}
if_stmt* if_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<if_stmt*>(pool->c_if_stmt(from_json_val_token(j["if_keyword"], pool),
      from_json_val_expr(j["expression"], pool),
      from_json_val_stmt(j["if_branch"], pool),
      from_json_val_token(j["else_keyword"], pool),
      from_json_val_stmt(j["else_branch"], pool)));
}
stmt *ast_pool::c_if_stmt(token* if_keyword, expr* expression, stmt* if_branch, token* else_keyword, stmt* else_branch) {
  auto o = new if_stmt(if_keyword, expression, if_branch, else_keyword, else_branch);
  cleanup_stmt_.push_back(o);
  return o;
}
import_stmt::import_stmt(token* import_token, std::vector<token*> import_names, token* name, file_info* data)
    : import_token_(import_token), import_names_(std::move(import_names)), name_(name), data_(data) {}
void import_stmt::accept(stmt_visitor *v) {
  v->visit_import_stmt(this);
}
ast_type import_stmt::get_type() {
  return ast_type::STMT_IMPORT;
}
token* import_stmt::locate() {
  return import_token_;
}
nlohmann::json import_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_import";
  j["import_token"] = to_json_val(import_token_);
  j["import_names"] = to_json_val(import_names_);
  j["name"] = to_json_val(name_);
  j["data"] = to_json_val(data_);
  return j;
}
import_stmt* import_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<import_stmt*>(pool->c_import_stmt(from_json_val_token(j["import_token"], pool),
      from_json_val_vector_helper(j["import_names"], [&](const nlohmann::json& item) { return from_json_val_token(item, pool); }),
      from_json_val_token(j["name"], pool),
      from_json_val_file_info(j["data"], pool)));
}
stmt *ast_pool::c_import_stmt(token* import_token, std::vector<token*> import_names, token* name, file_info* data) {
  auto o = new import_stmt(import_token, std::move(import_names), name, data);
  cleanup_stmt_.push_back(o);
  return o;
}
let_stmt::let_stmt(token* name, yk_datatype* data_type, expr* expression)
    : name_(name), data_type_(data_type), expression_(expression) {}
void let_stmt::accept(stmt_visitor *v) {
  v->visit_let_stmt(this);
}
ast_type let_stmt::get_type() {
  return ast_type::STMT_LET;
}
token* let_stmt::locate() {
  return name_;
}
nlohmann::json let_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_let";
  j["name"] = to_json_val(name_);
  j["data_type"] = to_json_val(data_type_);
  j["expression"] = to_json_val(expression_);
  return j;
}
let_stmt* let_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<let_stmt*>(pool->c_let_stmt(from_json_val_token(j["name"], pool),
      from_json_val_yk_datatype(j["data_type"], pool),
      from_json_val_expr(j["expression"], pool)));
}
stmt *ast_pool::c_let_stmt(token* name, yk_datatype* data_type, expr* expression) {
  auto o = new let_stmt(name, data_type, expression);
  cleanup_stmt_.push_back(o);
  return o;
}
nativeconst_stmt::nativeconst_stmt(token* name, yk_datatype* data_type, token* ccode_keyword, token* code_str, bool is_global)
    : name_(name), data_type_(data_type), ccode_keyword_(ccode_keyword), code_str_(code_str), is_global_(is_global) {}
void nativeconst_stmt::accept(stmt_visitor *v) {
  v->visit_nativeconst_stmt(this);
}
ast_type nativeconst_stmt::get_type() {
  return ast_type::STMT_NATIVECONST;
}
token* nativeconst_stmt::locate() {
  return name_;
}
nlohmann::json nativeconst_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_nativeconst";
  j["name"] = to_json_val(name_);
  j["data_type"] = to_json_val(data_type_);
  j["ccode_keyword"] = to_json_val(ccode_keyword_);
  j["code_str"] = to_json_val(code_str_);
  j["is_global"] = to_json_val(is_global_);
  return j;
}
nativeconst_stmt* nativeconst_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<nativeconst_stmt*>(pool->c_nativeconst_stmt(from_json_val_token(j["name"], pool),
      from_json_val_yk_datatype(j["data_type"], pool),
      from_json_val_token(j["ccode_keyword"], pool),
      from_json_val_token(j["code_str"], pool),
      from_json_val_bool(j["is_global"], pool)));
}
stmt *ast_pool::c_nativeconst_stmt(token* name, yk_datatype* data_type, token* ccode_keyword, token* code_str, bool is_global) {
  auto o = new nativeconst_stmt(name, data_type, ccode_keyword, code_str, is_global);
  cleanup_stmt_.push_back(o);
  return o;
}
pass_stmt::pass_stmt(token* pass_token)
    : pass_token_(pass_token) {}
void pass_stmt::accept(stmt_visitor *v) {
  v->visit_pass_stmt(this);
}
ast_type pass_stmt::get_type() {
  return ast_type::STMT_PASS;
}
token* pass_stmt::locate() {
  return pass_token_;
}
nlohmann::json pass_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_pass";
  j["pass_token"] = to_json_val(pass_token_);
  return j;
}
pass_stmt* pass_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<pass_stmt*>(pool->c_pass_stmt(from_json_val_token(j["pass_token"], pool)));
}
stmt *ast_pool::c_pass_stmt(token* pass_token) {
  auto o = new pass_stmt(pass_token);
  cleanup_stmt_.push_back(o);
  return o;
}
return_stmt::return_stmt(token* return_keyword, expr* expression, yk_datatype* result_type)
    : return_keyword_(return_keyword), expression_(expression), result_type_(result_type) {}
void return_stmt::accept(stmt_visitor *v) {
  v->visit_return_stmt(this);
}
ast_type return_stmt::get_type() {
  return ast_type::STMT_RETURN;
}
token* return_stmt::locate() {
  return return_keyword_;
}
nlohmann::json return_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_return";
  j["return_keyword"] = to_json_val(return_keyword_);
  j["expression"] = to_json_val(expression_);
  j["result_type"] = to_json_val(result_type_);
  return j;
}
return_stmt* return_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<return_stmt*>(pool->c_return_stmt(from_json_val_token(j["return_keyword"], pool),
      from_json_val_expr(j["expression"], pool),
      from_json_val_yk_datatype(j["result_type"], pool)));
}
stmt *ast_pool::c_return_stmt(token* return_keyword, expr* expression, yk_datatype* result_type) {
  auto o = new return_stmt(return_keyword, expression, result_type);
  cleanup_stmt_.push_back(o);
  return o;
}
runtimefeature_stmt::runtimefeature_stmt(token* runtimefeature_token, token* feature)
    : runtimefeature_token_(runtimefeature_token), feature_(feature) {}
void runtimefeature_stmt::accept(stmt_visitor *v) {
  v->visit_runtimefeature_stmt(this);
}
ast_type runtimefeature_stmt::get_type() {
  return ast_type::STMT_RUNTIMEFEATURE;
}
token* runtimefeature_stmt::locate() {
  return runtimefeature_token_;
}
nlohmann::json runtimefeature_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_runtimefeature";
  j["runtimefeature_token"] = to_json_val(runtimefeature_token_);
  j["feature"] = to_json_val(feature_);
  return j;
}
runtimefeature_stmt* runtimefeature_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<runtimefeature_stmt*>(pool->c_runtimefeature_stmt(from_json_val_token(j["runtimefeature_token"], pool),
      from_json_val_token(j["feature"], pool)));
}
stmt *ast_pool::c_runtimefeature_stmt(token* runtimefeature_token, token* feature) {
  auto o = new runtimefeature_stmt(runtimefeature_token, feature);
  cleanup_stmt_.push_back(o);
  return o;
}
while_stmt::while_stmt(token* while_keyword, expr* expression, stmt* while_body)
    : while_keyword_(while_keyword), expression_(expression), while_body_(while_body) {}
void while_stmt::accept(stmt_visitor *v) {
  v->visit_while_stmt(this);
}
ast_type while_stmt::get_type() {
  return ast_type::STMT_WHILE;
}
token* while_stmt::locate() {
  return while_keyword_;
}
nlohmann::json while_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_while";
  j["while_keyword"] = to_json_val(while_keyword_);
  j["expression"] = to_json_val(expression_);
  j["while_body"] = to_json_val(while_body_);
  return j;
}
while_stmt* while_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<while_stmt*>(pool->c_while_stmt(from_json_val_token(j["while_keyword"], pool),
      from_json_val_expr(j["expression"], pool),
      from_json_val_stmt(j["while_body"], pool)));
}
stmt *ast_pool::c_while_stmt(token* while_keyword, expr* expression, stmt* while_body) {
  auto o = new while_stmt(while_keyword, expression, while_body);
  cleanup_stmt_.push_back(o);
  return o;
}decl_stmt::decl_stmt(token* decl_token, token* name, std::vector<token*> replacement)
    : decl_token_(decl_token), name_(name), replacement_(std::move(replacement)) {}
ast_type decl_stmt::get_type() {
  return ast_type::STMT_DECL;
}
void decl_stmt::accept(stmt_visitor *v) {
}
token* decl_stmt::locate() {
  return name_;
}
nlohmann::json decl_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_decl";
  j["decl_token"] = to_json_val(decl_token_);
  j["name"] = to_json_val(name_);
  j["replacement"] = to_json_val(replacement_);
  return j;
}
decl_stmt* decl_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<decl_stmt*>(pool->c_decl_stmt(from_json_val_token(j["decl_token"], pool),
      from_json_val_token(j["name"], pool),
      from_json_val_vector_helper(j["replacement"], [&](const nlohmann::json& item) { return from_json_val_token(item, pool); })));
}
stmt *ast_pool::c_decl_stmt(token* decl_token, token* name, std::vector<token*> replacement) {
  auto o = new decl_stmt(decl_token, name, std::move(replacement));
  cleanup_stmt_.push_back(o);
  return o;
}
dsl_macro_stmt::dsl_macro_stmt(token* name, token* name2, token* not_symbol_tok, token* curly_open, std::vector<token*> internal_soup, token* curly_close)
    : name_(name), name2_(name2), not_symbol_tok_(not_symbol_tok), curly_open_(curly_open), internal_soup_(std::move(internal_soup)), curly_close_(curly_close) {}
ast_type dsl_macro_stmt::get_type() {
  return ast_type::STMT_DSL_MACRO;
}
void dsl_macro_stmt::accept(stmt_visitor *v) {
}
token* dsl_macro_stmt::locate() {
  return name_;
}
nlohmann::json dsl_macro_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_dsl_macro";
  j["name"] = to_json_val(name_);
  j["name2"] = to_json_val(name2_);
  j["not_symbol_tok"] = to_json_val(not_symbol_tok_);
  j["curly_open"] = to_json_val(curly_open_);
  j["internal_soup"] = to_json_val(internal_soup_);
  j["curly_close"] = to_json_val(curly_close_);
  return j;
}
dsl_macro_stmt* dsl_macro_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<dsl_macro_stmt*>(pool->c_dsl_macro_stmt(from_json_val_token(j["name"], pool),
      from_json_val_token(j["name2"], pool),
      from_json_val_token(j["not_symbol_tok"], pool),
      from_json_val_token(j["curly_open"], pool),
      from_json_val_vector_helper(j["internal_soup"], [&](const nlohmann::json& item) { return from_json_val_token(item, pool); }),
      from_json_val_token(j["curly_close"], pool)));
}
stmt *ast_pool::c_dsl_macro_stmt(token* name, token* name2, token* not_symbol_tok, token* curly_open, std::vector<token*> internal_soup, token* curly_close) {
  auto o = new dsl_macro_stmt(name, name2, not_symbol_tok, curly_open, std::move(internal_soup), curly_close);
  cleanup_stmt_.push_back(o);
  return o;
}
elif_stmt::elif_stmt(token* elif_keyword, expr* expression, stmt* elif_branch)
    : elif_keyword_(elif_keyword), expression_(expression), elif_branch_(elif_branch) {}
ast_type elif_stmt::get_type() {
  return ast_type::STMT_ELIF;
}
void elif_stmt::accept(stmt_visitor *v) {
}
token* elif_stmt::locate() {
  return elif_keyword_;
}
nlohmann::json elif_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_elif";
  j["elif_keyword"] = to_json_val(elif_keyword_);
  j["expression"] = to_json_val(expression_);
  j["elif_branch"] = to_json_val(elif_branch_);
  return j;
}
elif_stmt* elif_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<elif_stmt*>(pool->c_elif_stmt(from_json_val_token(j["elif_keyword"], pool),
      from_json_val_expr(j["expression"], pool),
      from_json_val_stmt(j["elif_branch"], pool)));
}
stmt *ast_pool::c_elif_stmt(token* elif_keyword, expr* expression, stmt* elif_branch) {
  auto o = new elif_stmt(elif_keyword, expression, elif_branch);
  cleanup_stmt_.push_back(o);
  return o;
}
macros_stmt::macros_stmt(token* macros_token, token* not_symbol_tok, token* curly_open, std::vector<token*> lisp_code, token* curly_close)
    : macros_token_(macros_token), not_symbol_tok_(not_symbol_tok), curly_open_(curly_open), lisp_code_(std::move(lisp_code)), curly_close_(curly_close) {}
ast_type macros_stmt::get_type() {
  return ast_type::STMT_MACROS;
}
void macros_stmt::accept(stmt_visitor *v) {
}
token* macros_stmt::locate() {
  return macros_token_;
}
nlohmann::json macros_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_macros";
  j["macros_token"] = to_json_val(macros_token_);
  j["not_symbol_tok"] = to_json_val(not_symbol_tok_);
  j["curly_open"] = to_json_val(curly_open_);
  j["lisp_code"] = to_json_val(lisp_code_);
  j["curly_close"] = to_json_val(curly_close_);
  return j;
}
macros_stmt* macros_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<macros_stmt*>(pool->c_macros_stmt(from_json_val_token(j["macros_token"], pool),
      from_json_val_token(j["not_symbol_tok"], pool),
      from_json_val_token(j["curly_open"], pool),
      from_json_val_vector_helper(j["lisp_code"], [&](const nlohmann::json& item) { return from_json_val_token(item, pool); }),
      from_json_val_token(j["curly_close"], pool)));
}
stmt *ast_pool::c_macros_stmt(token* macros_token, token* not_symbol_tok, token* curly_open, std::vector<token*> lisp_code, token* curly_close) {
  auto o = new macros_stmt(macros_token, not_symbol_tok, curly_open, std::move(lisp_code), curly_close);
  cleanup_stmt_.push_back(o);
  return o;
}
token_soup_stmt::token_soup_stmt(std::vector<token*> soup)
    : soup_(std::move(soup)) {}
ast_type token_soup_stmt::get_type() {
  return ast_type::STMT_TOKEN_SOUP;
}
void token_soup_stmt::accept(stmt_visitor *v) {
}
token* token_soup_stmt::locate() {
  return soup_[0];
}
nlohmann::json token_soup_stmt::to_json() {
  nlohmann::json j;
  j["ast_type"] = "stmt_token_soup";
  j["soup"] = to_json_val(soup_);
  return j;
}
token_soup_stmt* token_soup_stmt::from_json(const nlohmann::json& j, ast_pool* pool) {
  return static_cast<token_soup_stmt*>(pool->c_token_soup_stmt(from_json_val_vector_helper(j["soup"], [&](const nlohmann::json& item) { return from_json_val_token(item, pool); })));
}
stmt *ast_pool::c_token_soup_stmt(std::vector<token*> soup) {
  auto o = new token_soup_stmt(std::move(soup));
  cleanup_stmt_.push_back(o);
  return o;
}
// ------- utils ------
ast_pool::~ast_pool() {
  for (auto e : cleanup_expr_) {
    delete e;
  }
  for (auto e : cleanup_stmt_) {
    delete e;
  }
  cleanup_expr_.clear();
  cleanup_stmt_.clear();
}
ast_pool::ast_pool() {
  cleanup_expr_.reserve(1000);
  cleanup_stmt_.reserve(1000);
}